Fixed a conflict of symbols revealed by `inconsistency-check'(make check_iraf). It seems that imd_getseg() is not used from other files.
GCC's error messages are follows:

gcc  -DSPP_ILP64 -c  -O -Wall -I/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include idk.c
In file included from /home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/sys/imd.h:4,
                 from f2c_include.h:5,
                 from idk.c:13:
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/sys/../../../../sys/gio/imdkern/f2c_proto.h:23: error: conflicting types for 'imdgeg_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/images/tv/display/f2c_proto.h:43: error: previous declaration of 'imdgeg_' was here
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/sys/../../../../sys/gio/imdkern/f2c_proto.h:23: error: conflicting types for 'imdgeg_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/images/tv/display/f2c_proto.h:43: error: previous declaration of 'imdgeg_' was here




git-svn-id: https://svn.code.sf.net/p/iraf64/code/trunk/src@45 0682cb55-6b43-0410-8320-9b94b4336a91