Fixed some conflicts of symbols revealed by `inconsistency-check'(make check_iraf).
GCC's error messages are follows:

igcc  -DSPP_ILP64 -c  -O -Wall -I/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include t_implot.c
t_implot.c:31: error: 'impcom_' redeclared as different kind of symbol
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/sys/../../../../sys/imio/dbc/f2c_proto.h:18: error: previous decl
aration of 'impcom_' was here
t_implot.c:31: error: 'impcom_' redeclared as different kind of symbol
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/sys/../../../../sys/imio/dbc/f2c_proto.h:18: error: previous decl
aration of 'impcom_' was here

gcc  -DSPP_ILP64 -c  -O -Wall -I/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include intrp.c
In file included from f2c_include.h:7,
                 from intrp.c:13:
f2c_proto.h:34: error: conflicting types for 'intrp_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:1: error: previous declaration of 'intrp_' was here
f2c_proto.h:34: error: conflicting types for 'intrp_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:1: error: previous declaration of 'intrp_' was here
f2c_proto.h:35: error: conflicting types for 'srch_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:3: error: previous declaration of 'srch_' was here
f2c_proto.h:35: error: conflicting types for 'srch_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:3: error: previous declaration of 'srch_' was here
f2c_proto.h:38: error: conflicting types for 'codim1_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:6: error: previous declaration of 'codim1_' was here
f2c_proto.h:38: error: conflicting types for 'codim1_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:6: error: previous declaration of 'codim1_' was here
f2c_proto.h:39: error: conflicting types for 'lintrp_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:7: error: previous declaration of 'lintrp_' was here
f2c_proto.h:39: error: conflicting types for 'lintrp_'
/home_afpl02/cyamauch/work/iraf/sf_svn/iraf64/trunk/src/iraf/unix/include/f2c/pkg/../../../../pkg/xtools/f2c_proto.h:7: error: previous declaration of 'lintrp_' was here



git-svn-id: https://svn.code.sf.net/p/iraf64/code/trunk/src@43 0682cb55-6b43-0410-8320-9b94b4336a91